### ISSUE TITLE
Virtual webcam

### ISSUE THREAD

**Issue by DasKatzchen** [pi-null-mezon/QPULSECAPTURE#1]
Would it be possible to add a virtual webcam to the program, so you could stream your pulse rate in Skype or hangouts or whatever? I found some information about virtual webcams [here](https://social.msdn.microsoft.com/forums/windowsdesktop/en-US/574489eb-b2bc-4f3f-b644-7fd2264d59f4/directshow-desktop-capture-and-output). It would also need an option to hide the green mask. I know it's a bit niche, but I think it would be useful.

**Comment by pi-null-mezon** [comment]
Oh virtual webcam feature probably would be nice, but seems to me that this task demands a lot of time and work, so I can not done it very fast. But be sure, green mask option will be added in next release

**Comment by pi-null-mezon** [comment]
After some searching I have found that there is a lot of 3rd parties application that can make virtual webcam (for the instance VLC with VCam plugin or WebcamMax). Skype also supports desktop video <a href="http://superuser.com/questions/633655/how-to-pass-stream-to-skype">sharing</a>.

**Comment by DasKatzchen** [comment]
I didn't know that you could do screen sharing on Skype.  That will be very useful, thanks. It would still be cool to have native support, though.
